import { IIndividualReviewCard } from './IndividualReviewSlider.types';

export const data: IIndividualReviewCard[] = [
    {
        id: 1,
        name: 'Randolph Nash',
        title: 'Wonderful painting',
        content: 'P2p has a good service and affordable prices. Loved the resu...',
        rate: 4,
        date: '26 Mar 2023',
    },
    {
        id: 2,
        name: 'Homer Moody',
        title: 'The best decision I made',
        content: 'I saw videos of reveals for this site on Facebook. Of course...',
        rate: 5,
        date: '25 Mar 2023',
    },
    {
        id: 3,
        name: 'Harvey Chapman',
        title: 'Incredible',
        content: 'Happy with the painting and the frame. P2p staff give each c...',
        rate: 5,
        date: '20 Mar 2023',
    },
    {
        id: 4,
        name: 'Cathleen Smith',
        title: 'Perfect!',
        content: 'I am excited about the time it took to deliver the paintings...',
        rate: 5,
        date: '18 Mar 2023',
    },
    {
        id: 5,
        name: 'Rene Castillo',
        title: 'Great gift',
        content: 'This is a great gift to the person, it made the recipient&rs...',
        rate: 5,
        date: '17 Mar 2023',
    },
    {
        id: 6,
        name: 'Newman Luis',
        title: 'Perfect painting',
        content: 'Excellent Service and excellent quality.Communication was qu...',
        rate: 5,
        date: '22 Mar 2022',
    },
    {
        id: 7,
        name: 'Johnson Edwin',
        title: 'WOW!!',
        content: 'The picture is fantastic! I grabbed photographs from my brot...',
        rate: 5,
        date: '22 Mar 2022',
    },
    {
        id: 8,
        name: 'Dustin Briggs',
        title: 'I very much recommend photo2painting',
        content: 'I made the mistake of selecting the incorrect style for the ...',
        rate: 4,
        date: '21 Dec 2022',
    },
    {
        id: 9,
        name: 'Tim Cameron',
        title: "It's unbelievable",
        content: 'Simply fantastic. There are no words to describe the exquisi...',
        rate: 5,
        date: '20 Dec 2022',
    },
    {
        id: 10,
        name: 'Adrian Campball',
        title: 'Beautiful',
        content: 'Beautifully created, looking forward to gifting it to my sis...',
        rate: 4,
        date: '18 Dec 2022',
    },
];
